apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitheroes-guide-bot-statefulset
  labels:
    app: bitheroes-guide-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitheroes-guide-bot
  template:
    metadata:
      labels:
        app: bitheroes-guide-bot
    spec:
      containers:
      - name: bitheroes-guide-bot 
        image: deadloct/bitheroes-guide-bot:latest
        env:
        - name: BITHEROES_GUIDE_BOT_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
                name: bitheroes-guide-bot-secrets
                key: BITHEROES_GUIDE_BOT_AUTH_TOKEN
